load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "khir_program",
    srcs = ["khir_program.cc"],
    hdrs = ["khir_program.h"],
    deps = [
        "@type_safe",
    ],
)
